name: branch_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: check
        uses: abystoma/external-workflow@branch
      - name: Greetings
        run: echo "$(<greetings.txt)"